'use client'

import { useState, useEffect } from 'react'
import { StaffService, Staff, CreateStaffRequest, UpdateStaffRequest } from '@/services/staffService'
import { Button } from '@/components/ui/Button'
import { LoadingSpinner } from '@/components/ui/LoadingSpinner'
import { StoreLocation } from '@/services/storeLocationService'
import { User, Mail, Phone, MapPin, Store, X, Eye, EyeOff } from 'lucide-react'
import toast from 'react-hot-toast'
import { motion } from 'framer-motion'

interface StaffModalProps {
  staff: Staff | null
  stores: StoreLocation[]
  onClose: () => void
  onSave: () => void
}

export default function StaffModal({ staff, stores, onClose, onSave }: StaffModalProps) {
  const [loading, setLoading] = useState(false)
  const [showPassword, setShowPassword] = useState(false)
  const [selectedStore, setSelectedStore] = useState<StoreLocation | null>(null)
  const [formData, setFormData] = useState({
    username: '',
    email: '',
    password: '',
    phoneNumber: '',
    address: '',
    storeLocationId: undefined as number | undefined
  })

  useEffect(() => {
    if (staff) {
      const store = stores.find(s => 
        (s.id || (s as any).locationID) === (staff.storeLocationId || staff.storeLocation?.locationID)
      )
      setSelectedStore(store || null)
      setFormData({
        username: staff.username || '',
        email: staff.email || '',
        password: '',
        phoneNumber: staff.phoneNumber || '',
        address: staff.address || '',
        storeLocationId: staff.storeLocationId || staff.storeLocation?.locationID
      })
    } else {
      setSelectedStore(null)
      setFormData({
        username: '',
        email: '',
        password: '',
        phoneNumber: '',
        address: '',
        storeLocationId: undefined
      })
    }
  }, [staff, stores])

  const handleStoreChange = (storeId: number | undefined) => {
    if (!storeId) {
      setSelectedStore(null)
      setFormData({
        username: '',
        email: '',
        password: formData.password,
        phoneNumber: '',
        address: '',
        storeLocationId: undefined
      })
      return
    }

    const store = stores.find(s => (s.id || (s as any).locationID) === storeId)
    if (store) {
      setSelectedStore(store)
      
      if (!staff) {
        // Auto-fill for new staff
        const storeName = store.name
        const storePhone = store.phone || store.phoneNumber || ''
        const storeAddress = store.address || ''
        const storeId = store.id || (store as any).locationID || ''
        const storeEmail = store.email || ''
        
        // Username will be auto-generated by backend with format: staff_ + normalizedStoreName + _ + staffId
        // So we leave it empty or show preview
        const normalizedStoreName = storeName
          .toLowerCase()
          .normalize('NFD')
          .replace(/[\u0300-\u036f]/g, '')
          .replace(/[^a-z0-9\s]/g, '')
          .replace(/\s+/g, '')
        // Preview username (will be updated by backend with actual staff id)
        const usernamePreview = `staff_${normalizedStoreName}_[id]`
        
        // Email: Use store email (required)
        const email = storeEmail
        
        setFormData({
          username: '', // Leave empty, backend will generate with staff id
          email,
          password: formData.password,
          phoneNumber: storePhone,
          address: storeAddress,
          storeLocationId: storeId
        })
      } else {
        // For editing, just update storeLocationId
        setFormData({
          ...formData,
          storeLocationId: storeId
        })
      }
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!staff && !formData.storeLocationId) {
      toast.error('Vui lòng chọn cửa hàng để tạo nhân viên')
      return
    }

    if (!staff && !formData.password.trim()) {
      toast.error('Vui lòng nhập mật khẩu cho nhân viên mới')
      return
    }

    if (!staff && formData.password.length < 6) {
      toast.error('Mật khẩu phải có ít nhất 6 ký tự')
      return
    }

    // Validate username: no spaces allowed
    if (formData.username && /\s/.test(formData.username)) {
      toast.error('Tên đăng nhập không được chứa khoảng trắng')
      return
    }

    try {
      setLoading(true)

      if (staff) {
        // Update staff
        const updateData: UpdateStaffRequest = {
          username: formData.username,
          email: formData.email,
          phoneNumber: formData.phoneNumber || undefined,
          address: formData.address || undefined,
          storeLocationId: formData.storeLocationId || undefined
        }
        
        await StaffService.updateStaff(staff.userID, updateData)
        toast.success('Cập nhật nhân viên thành công')
      } else {
        // Create staff
        const createData: CreateStaffRequest = {
          username: formData.username,
          email: formData.email,
          password: formData.password,
          phoneNumber: formData.phoneNumber || undefined,
          address: formData.address || undefined,
          storeLocationId: formData.storeLocationId || undefined
        }
        
        await StaffService.createStaff(createData)
        toast.success('Tạo nhân viên thành công')
      }

      onSave()
    } catch (error: any) {
      console.error('Error saving staff:', error)
      toast.error(error.message || 'Không thể lưu thông tin nhân viên')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4" onClick={onClose}>
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        onClick={(e) => e.stopPropagation()}
        className="bg-white rounded-xl shadow-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto"
      >
        {/* Header */}
        <div className="sticky top-0 bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-violet-100 rounded-lg flex items-center justify-center">
              <User className="w-5 h-5 text-violet-600" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-gray-900">
                {staff ? 'Sửa nhân viên' : 'Thêm nhân viên mới'}
              </h2>
              <p className="text-sm text-gray-500">
                {staff ? 'Cập nhật thông tin và phân công cửa hàng' : 'Tạo tài khoản nhân viên mới'}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
          >
            <X className="w-5 h-5 text-gray-500" />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="p-6 space-y-6">
          {/* Store Assignment - Moved to top */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Phân công cửa hàng <span className="text-red-500">*</span>
            </label>
            <div className="relative">
              <Store className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
              <select
                value={formData.storeLocationId || ''}
                onChange={(e) => handleStoreChange(e.target.value ? parseInt(e.target.value) : undefined)}
                className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-violet-500 focus:border-transparent appearance-none bg-white"
                disabled={loading || !!staff}
                required={!staff}
              >
                <option value="">{staff ? 'Chưa phân công' : 'Chọn cửa hàng...'}</option>
                {stores.map((store) => (
                  <option key={store.id || (store as any).locationID} value={store.id || (store as any).locationID}>
                    {store.name} - {store.address}
                  </option>
                ))}
              </select>
            </div>
            {!staff && (
              <p className="text-xs text-gray-500 mt-1">
                Thông tin nhân viên sẽ được tự động điền từ cửa hàng đã chọn.
              </p>
            )}
            {staff && (
              <p className="text-xs text-gray-500 mt-1">
                Mỗi cửa hàng chỉ có thể được phân công cho 1 nhân viên. Nếu cửa hàng đã có nhân viên, bạn cần gỡ phân công trước.
              </p>
            )}
          </div>

          {/* Auto-filled info from store (read-only for new staff) */}
          {!staff && selectedStore && (
            <>
              {/* Username - Auto-filled, read-only */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Tên đăng nhập
                </label>
                <div className="relative">
                  <User className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                  <input
                    type="text"
                    value={formData.username}
                    className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg bg-gray-50 text-gray-600"
                    readOnly
                    disabled
                  />
                </div>
                <p className="text-xs text-gray-500 mt-1">Tự động tạo từ tên cửa hàng</p>
              </div>

              {/* Email - Auto-filled, read-only */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Email
                </label>
                <div className="relative">
                  <Mail className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                  <input
                    type="email"
                    value={formData.email}
                    className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg bg-gray-50 text-gray-600"
                    readOnly
                    disabled
                  />
                </div>
                <p className="text-xs text-gray-500 mt-1">Tự động tạo từ thông tin cửa hàng</p>
              </div>

              {/* Phone - Auto-filled, read-only */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Số điện thoại
                </label>
                <div className="relative">
                  <Phone className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                  <input
                    type="tel"
                    value={formData.phoneNumber}
                    className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg bg-gray-50 text-gray-600"
                    readOnly
                    disabled
                  />
                </div>
                <p className="text-xs text-gray-500 mt-1">Lấy từ thông tin cửa hàng</p>
              </div>

              {/* Address - Auto-filled, read-only */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Địa chỉ
                </label>
                <div className="relative">
                  <MapPin className="absolute left-3 top-3 w-5 h-5 text-gray-400" />
                  <textarea
                    value={formData.address}
                    className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg bg-gray-50 text-gray-600"
                    rows={2}
                    readOnly
                    disabled
                  />
                </div>
                <p className="text-xs text-gray-500 mt-1">Lấy từ địa chỉ cửa hàng</p>
              </div>
            </>
          )}

          {/* Editable fields for editing staff */}
          {staff && (
            <>
              {/* Username */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Tên đăng nhập <span className="text-red-500">*</span>
                </label>
                <div className="relative">
                  <User className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                  <input
                    type="text"
                    value={formData.username}
                    onChange={(e) => setFormData({ ...formData, username: e.target.value })}
                    className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-violet-500 focus:border-transparent"
                    placeholder="Nhập tên đăng nhập"
                    required
                    disabled={loading}
                  />
                </div>
              </div>

              {/* Email */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Email <span className="text-red-500">*</span>
                </label>
                <div className="relative">
                  <Mail className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                  <input
                    type="email"
                    value={formData.email}
                    onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                    className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-violet-500 focus:border-transparent"
                    placeholder="Nhập email"
                    required
                    disabled={loading}
                  />
                </div>
              </div>

              {/* Phone */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Số điện thoại
                </label>
                <div className="relative">
                  <Phone className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                  <input
                    type="tel"
                    value={formData.phoneNumber}
                    onChange={(e) => setFormData({ ...formData, phoneNumber: e.target.value })}
                    className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-violet-500 focus:border-transparent"
                    placeholder="Nhập số điện thoại"
                    disabled={loading}
                  />
                </div>
              </div>

              {/* Address */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Địa chỉ
                </label>
                <div className="relative">
                  <MapPin className="absolute left-3 top-3 w-5 h-5 text-gray-400" />
                  <textarea
                    value={formData.address}
                    onChange={(e) => setFormData({ ...formData, address: e.target.value })}
                    className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-violet-500 focus:border-transparent"
                    placeholder="Nhập địa chỉ"
                    rows={2}
                    disabled={loading}
                  />
                </div>
              </div>
            </>
          )}

          {/* Password (only for new staff) */}
          {!staff && (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Mật khẩu <span className="text-red-500">*</span>
              </label>
              <div className="relative">
                <User className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  type={showPassword ? 'text' : 'password'}
                  value={formData.password}
                  onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                  className="w-full pl-10 pr-10 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-violet-500 focus:border-transparent"
                  placeholder="Nhập mật khẩu (tối thiểu 6 ký tự)"
                  required
                  disabled={loading}
                  minLength={6}
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600"
                >
                  {showPassword ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
                </button>
              </div>
            </div>
          )}

          {/* Actions */}
          <div className="flex justify-end gap-3 pt-4 border-t border-gray-200">
            <Button
              type="button"
              variant="outline"
              onClick={onClose}
              disabled={loading}
            >
              Hủy
            </Button>
            <Button
              type="submit"
              disabled={loading}
              className="bg-violet-600 hover:bg-violet-700"
            >
              {loading ? (
                <>
                  <LoadingSpinner size="sm" className="mr-2" />
                  Đang lưu...
                </>
              ) : (
                staff ? 'Cập nhật' : 'Tạo nhân viên'
              )}
            </Button>
          </div>
        </form>
      </motion.div>
    </div>
  )
}

